name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: gh-pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rustup
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y && source "$HOME/.cargo/env"
      - name: Install Rust WASM Target
        run: rustup target add wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install trunk
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install JavaScript Dependencies
        run: yarn
      - name: Build Project
        run: trunk build --public-url ${{ github.event.repository.name }}/
      - name: Upload Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
